name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Blocklet workflow
        uses: blocklet/action-workflow@v1
        with:
          skip-upload: true
          skip-deploy: true
          bundle-command: blocklet bundle --create-release
          github-token: ${{ secrets.GITHUB_TOKEN }}